// ogrenci_verileri.js
// Excel'deki öğrenci listesi buraya JSON formatında aktarılır.
const studentDatabase = [
    // 9. Sınıf / A Şubesi
    { no: "2422", ad: "DAMLA ZEHRA", soyad: "KELEŞ", sinif: "9-A" },
    { no: "2454", ad: "İSMAİL YİĞİT", soyad: "İNCİ", sinif: "9-A" },
    { no: "2500", ad: "ESRA HİLAL", soyad: "AY", sinif: "9-A" },
    { no: "2501", ad: "SARE", soyad: "TAŞ", sinif: "9-A" },
    { no: "2502", ad: "ELA", soyad: "ÇEVİK", sinif: "9-A" },
    { no: "2503", ad: "YAĞMUR", soyad: "TANTANOĞLU", sinif: "9-A" },
    { no: "2504", ad: "SENANUR", soyad: "DEMİRKAN", sinif: "9-A" },
    { no: "2505", ad: "YUNUS EMRE", soyad: "IRMAK", sinif: "9-A" },
    { no: "2506", ad: "NESLİHAN AZRA", soyad: "ÖZ", sinif: "9-A" },
    { no: "2507", ad: "ZEYNEP YAĞMUR", soyad: "ZEYBEK", sinif: "9-A" },
    { no: "2508", ad: "ELİF TUANA", soyad: "CİNGÖZGİL", sinif: "9-A" },
    { no: "2509", ad: "ALPEREN", soyad: "OKUMUŞ", sinif: "9-A" },
    { no: "2510", ad: "ÖYKÜ BERİL", soyad: "ARSLAN", sinif: "9-A" },
    { no: "2511", ad: "SÜVEYDA NUR", soyad: "YÜTÜK", sinif: "9-A" },
    { no: "2512", ad: "UMAY KATRE", soyad: "ULUKANLI", sinif: "9-A" },
    { no: "2513", ad: "EBRU", soyad: "AVCI", sinif: "9-A" },
    { no: "2514", ad: "SERDAR YAŞAR", soyad: "BAHADIR", sinif: "9-A" },
    { no: "2515", ad: "YÜSRANUR", soyad: "MUTLU", sinif: "9-A" },
    { no: "2516", ad: "BURAK", soyad: "ÜZÜMCÜOĞLU", sinif: "9-A" },
    { no: "2517", ad: "METE", soyad: "ZORLU", sinif: "9-A" },
    { no: "2519", ad: "ATİLLA", soyad: "SARGUT", sinif: "9-A" },
    { no: "2520", ad: "METİN BERAT", soyad: "TEKELİ", sinif: "9-A" },
    { no: "2521", ad: "YUSUF", soyad: "SARAÇ", sinif: "9-A" },
    { no: "2522", ad: "NİSANUR", soyad: "ÖZELCİ", sinif: "9-A" },
    { no: "2523", ad: "MEHMET YİĞİT", soyad: "YILDIZ", sinif: "9-A" },
    { no: "2524", ad: "MERT ALİ", soyad: "BEKCİ", sinif: "9-A" },
    { no: "2525", ad: "MERVE", soyad: "GÜNGÖR", sinif: "9-A" },

    // 9. Sınıf / B Şubesi
    { no: "2443", ad: "RÜMEYSA NUR", soyad: "ÜNLÜK", sinif: "9-B" },
    { no: "2451", ad: "ABDULLAH TALHA", soyad: "ACAR", sinif: "9-B" },
    { no: "2459", ad: "ŞEVVAL", soyad: "UĞUR", sinif: "9-B" },
    { no: "2461", ad: "MEVA ÇAĞLA", soyad: "ÇALIŞ", sinif: "9-B" },
    { no: "2463", ad: "AZİME GÜL", soyad: "UĞUR", sinif: "9-B" },
    { no: "2540", ad: "ATAKAN", soyad: "ÜSTÜNDAĞ", sinif: "9-B" },
    { no: "2541", ad: "FURKAN", soyad: "SARAÇ", sinif: "9-B" },
    { no: "2542", ad: "YAĞIZ ALP", soyad: "GÖKYAR", sinif: "9-B" },
    { no: "2543", ad: "NECMİ EFE", soyad: "ORAL", sinif: "9-B" },
    { no: "2544", ad: "EMİRHAN", soyad: "EKREM", sinif: "9-B" },
    { no: "2545", ad: "BEREN NİSA", soyad: "ESEN", sinif: "9-B" },
    { no: "2546", ad: "ELİF", soyad: "İMREN", sinif: "9-B" },
    { no: "2547", ad: "EBRU", soyad: "CİN", sinif: "9-B" },
    { no: "2548", ad: "EBRARNUR", soyad: "GÖKYAR", sinif: "9-B" },
    { no: "2549", ad: "RAVZA NUR", soyad: "DİLEK", sinif: "9-B" },
    { no: "2550", ad: "ASUMAN CEREN", soyad: "KIRAN", sinif: "9-B" },
    { no: "2551", ad: "BERAT", soyad: "KİRİŞ", sinif: "9-B" },
    { no: "2552", ad: "BUSEGÜL", soyad: "DEMİREL", sinif: "9-B" },
    { no: "2553", ad: "NİSANUR", soyad: "GÜLER", sinif: "9-B" },
    { no: "2554", ad: "KÜBRA", soyad: "KILAVUZ", sinif: "9-B" },
    { no: "2555", ad: "ZEYNEP", soyad: "SARIOĞLU", sinif: "9-B" },
    { no: "2556", ad: "HÜLYA", soyad: "MENDEŞ", sinif: "9-B" },
    { no: "2557", ad: "EBRAR", soyad: "GÜN", sinif: "9-B" },
    { no: "2558", ad: "CEMRE", soyad: "ELMACI", sinif: "9-B" },
    { no: "2559", ad: "YAĞMUR", soyad: "BÜYÜKSARI", sinif: "9-B" },
    { no: "2560", ad: "AYŞENUR", soyad: "ÇELEBİ", sinif: "9-B" },
    { no: "2561", ad: "İLAYDA NUR", soyad: "ÖZBİLEN", sinif: "9-B" },
    { no: "2562", ad: "MUHAMMED ALİ", soyad: "YOLCU", sinif: "9-B" },
    { no: "2563", ad: "İBRAHİM POYRAZ", soyad: "ÖZDEMİR", sinif: "9-B" },

    // 9. Sınıf / C Şubesi
    { no: "2487", ad: "KÜBRA", soyad: "YİĞİT", sinif: "9-C" },
    { no: "2490", ad: "SERHAT", soyad: "MECEK", sinif: "9-C" },
    { no: "2570", ad: "İSMAİL EFE", soyad: "DEVREZ", sinif: "9-C" },
    { no: "2571", ad: "ZEYNEP", soyad: "OKUDUCU", sinif: "9-C" },
    { no: "2572", ad: "BERKAY", soyad: "ÇAMLICALI", sinif: "9-C" },
    { no: "2573", ad: "HÜSEYİN EFE", soyad: "CIBIROĞLU", sinif: "9-C" },
    { no: "2574", ad: "ZEYNEP SU", soyad: "UYSAL", sinif: "9-C" },
    { no: "2575", ad: "EDA NUR", soyad: "YILDIZ", sinif: "9-C" },
    { no: "2576", ad: "MELİS NİSA", soyad: "BASUTCU", sinif: "9-C" },
    { no: "2577", ad: "ECRİN İLAYDA", soyad: "DOĞANALP", sinif: "9-C" },
    { no: "2578", ad: "ALİ OSMAN", soyad: "OĞUZ", sinif: "9-C" },
    { no: "2579", ad: "AHMET DOĞAN", soyad: "ÇINAR", sinif: "9-C" },
    { no: "2580", ad: "ALİ İHSAN", soyad: "NALBAT", sinif: "9-C" },
    { no: "2581", ad: "BERTUĞ TUANA", soyad: "DURMUŞ", sinif: "9-C" },
    { no: "2583", ad: "NİSANUR", soyad: "BEZCİOĞLU", sinif: "9-C" },
    { no: "2585", ad: "CEM BULUT", soyad: "ÇOLAK", sinif: "9-C" },
    { no: "2586", ad: "KUZEY TAHA", soyad: "PELİN", sinif: "9-C" },
    { no: "2587", ad: "BETÜL", soyad: "AKYILDIZ", sinif: "9-C" },

    // 10. Sınıf / A Şubesi
    { no: "2312", ad: "ELİF NUR", soyad: "SİVRİOĞLU", sinif: "10-A" },
    { no: "2314", ad: "SUDE ZEYNEP", soyad: "REÇBER", sinif: "10-A" },
    { no: "2319", ad: "MÜNİRE BETÜL", soyad: "KÜÇÜKKESKİN", sinif: "10-A" },
    { no: "2341", ad: "MERT OSMAN", soyad: "KURTCUOĞLU", sinif: "10-A" },
    { no: "2401", ad: "ESRA", soyad: "YİĞİT", sinif: "10-A" },
    { no: "2405", ad: "ECRİN", soyad: "ÇEVİK", sinif: "10-A" },
    { no: "2406", ad: "ŞEVVAL SERAP", soyad: "DURAK", sinif: "10-A" },
    { no: "2407", ad: "BERAY", soyad: "ATEŞOĞLU", sinif: "10-A" },
    { no: "2408", ad: "SÜMEYYE GÜL", soyad: "MARULCU", sinif: "10-A" },
    { no: "2410", ad: "SUDENAZ", soyad: "KIRAÇ", sinif: "10-A" },
    { no: "2411", ad: "DUYGU", soyad: "ÇATMIŞ", sinif: "10-A" },
    { no: "2414", ad: "ESRA", soyad: "YİĞİT", sinif: "10-A" },
    { no: "2415", ad: "SEDA", soyad: "ÇÖLMEKOĞLU", sinif: "10-A" },
    { no: "2416", ad: "TUĞBA", soyad: "PİRİZOĞLU", sinif: "10-A" },
    { no: "2418", ad: "HAYRÜNNİSA", soyad: "GÜL", sinif: "10-A" },
    { no: "2420", ad: "GAMZE", soyad: "KADER", sinif: "10-A" },
    { no: "2425", ad: "İKRA NUR", soyad: "TAŞ", sinif: "10-A" },
    { no: "2427", ad: "KÜRŞAD EFE", soyad: "ÇİLİNGİR", sinif: "10-A" },
    { no: "2428", ad: "ÖZGÜL", soyad: "ÖZDEMİR", sinif: "10-A" },
    { no: "2442", ad: "YAZEL ELA", soyad: "KÜÇÜKDEDE", sinif: "10-A" },
    { no: "2447", ad: "ALPEREN", soyad: "ÖZURGANCI", sinif: "10-A" },
    { no: "2448", ad: "EMİRHAN", soyad: "KILIÇ", sinif: "10-A" },
    { no: "2449", ad: "RECEP FURKAN", soyad: "SOYDAN", sinif: "10-A" },
    { no: "2455", ad: "EDANUR", soyad: "YİĞİT", sinif: "10-A" },
    { no: "2460", ad: "ELİF NUR", soyad: "OKUYUCU", sinif: "10-A" },

    // 10. Sınıf / B Şubesi
    { no: "2310", ad: "MİNE FATMA", soyad: "ÜNAL", sinif: "10-B" },
    { no: "2317", ad: "KAYRA PINAR", soyad: "ARI", sinif: "10-B" },
    { no: "2352", ad: "MUHAMMET ARSLAN", soyad: "KUZBUNAR", sinif: "10-B" },
    { no: "2353", ad: "GÖKTUĞ ATA", soyad: "TÜRK", sinif: "10-B" },
    { no: "2359", ad: "RAMAZAN", soyad: "BEZCİOĞLU", sinif: "10-B" },
    { no: "2361", ad: "UMUT EREN", soyad: "KARA", sinif: "10-B" },
    { no: "2402", ad: "FURKAN", soyad: "OKUMUŞ", sinif: "10-B" },
    { no: "2409", ad: "ECRİN LENA", soyad: "KIRIŞ", sinif: "10-B" },
    { no: "2412", ad: "EFECAN", soyad: "ARKAN", sinif: "10-B" },
    { no: "2417", ad: "KEVSER", soyad: "ELÇİ", sinif: "10-B" },
    { no: "2419", ad: "İSMAİL SEFA", soyad: "MARANGOZ", sinif: "10-B" },
    { no: "2421", ad: "BEYZA NUR", soyad: "AYRANCI", sinif: "10-B" },
    { no: "2423", ad: "ÖMER ASAF", soyad: "KÜÇÜKMORKOÇ", sinif: "10-B" },
    { no: "2429", ad: "ELİF SUDE", soyad: "KOÇ", sinif: "10-B" },
    { no: "2441", ad: "EBRAR", soyad: "GÖMLEKSİZ", sinif: "10-B" },
    { no: "2444", ad: "ZEYNEP", soyad: "KÖSEOĞLU", sinif: "10-B" },
    { no: "2445", ad: "FURKAN KEMAL", soyad: "KUMRU", sinif: "10-B" },
    { no: "2450", ad: "ÖMER FARUK", soyad: "OCAKLI", sinif: "10-B" },
    { no: "2453", ad: "EROL EFE", soyad: "UÇAR", sinif: "10-B" },
    { no: "2456", ad: "GÜLDANE", soyad: "GÖK", sinif: "10-B" },
    { no: "2457", ad: "ESİLA ALYA", soyad: "ORUÇ", sinif: "10-B" },
    { no: "2458", ad: "CELİL", soyad: "TESTİCİ", sinif: "10-B" },
    { no: "2462", ad: "CANSU", soyad: "ZEYBEK", sinif: "10-B" },
    { no: "2465", ad: "ENES", soyad: "KUMCU", sinif: "10-B" },
    { no: "2467", ad: "NAZLI YAREN", soyad: "YÖRÜK", sinif: "10-B" },

    // 10. Sınıf / C Şubesi
    { no: "2384", ad: "MUHAMMET MUSTAFA", soyad: "MENSUR", sinif: "10-C" },
    { no: "2388", ad: "MERT", soyad: "PEHLİVAN", sinif: "10-C" },
    { no: "2480", ad: "ECRİN SUDE", soyad: "UYGUN", sinif: "10-C" },
    { no: "2482", ad: "ECRİN", soyad: "TÜRKMEN", sinif: "10-C" },
    { no: "2484", ad: "YUSUF", soyad: "EMEKLİ", sinif: "10-C" },
    { no: "2485", ad: "NİLÜFER ASYA", soyad: "AKI", sinif: "10-C" },
    { no: "2486", ad: "PINAR", soyad: "POZUKCU", sinif: "10-C" },
    { no: "2488", ad: "ELİF", soyad: "ERKAYA", sinif: "10-C" },
    { no: "2489", ad: "BELKIZ", soyad: "KOÇAK", sinif: "10-C" },
    { no: "2491", ad: "UMUT BAKİ", soyad: "CAN", sinif: "10-C" },
    { no: "2492", ad: "AHMET MELİH", soyad: "ÖZİPEK", sinif: "10-C" },

    // 11. Sınıf / A Şubesi
    { no: "2302", ad: "EMİRHAN", soyad: "ESER", sinif: "11-A" },
    { no: "2307", ad: "MEDİNE", soyad: "İNCİ", sinif: "11-A" },
    { no: "2309", ad: "ELANUR", soyad: "CAN", sinif: "11-A" },
    { no: "2321", ad: "NURBANU", soyad: "ÖZDEMİR", sinif: "11-A" },
    { no: "2325", ad: "ESMA", soyad: "KAYACI", sinif: "11-A" },
    { no: "2326", ad: "SEMRA NAZ", soyad: "GÖKÇE", sinif: "11-A" },
    { no: "2327", ad: "MELİH", soyad: "UZUN", sinif: "11-A" },
    { no: "2328", ad: "RUMEYSA", soyad: "ŞEREFLİ", sinif: "11-A" },
    { no: "2329", ad: "BERAT", soyad: "KÖSE", sinif: "11-A" },
    { no: "2332", ad: "KÜBRA", soyad: "YÖRECİ", sinif: "11-A" },
    { no: "2334", ad: "ESMA", soyad: "YAĞCI", sinif: "11-A" },
    { no: "2340", ad: "SÜMEYRA NUR", soyad: "POLAT", sinif: "11-A" },
    { no: "2345", ad: "MEHMET EFE", soyad: "CİNHASAN", sinif: "11-A" },
    { no: "2347", ad: "DUYGU", soyad: "GÖZCÜ", sinif: "11-A" },
    { no: "2348", ad: "BETÜL", soyad: "KÜRECİ", sinif: "11-A" },
    { no: "2350", ad: "EYYÜP", soyad: "TÖL", sinif: "11-A" },
    { no: "2351", ad: "NİSA NUR", soyad: "ORUÇOĞLU", sinif: "11-A" },
    { no: "2355", ad: "SELÇUK", soyad: "ÇATKIN", sinif: "11-A" },
    { no: "2356", ad: "İREM", soyad: "BEDESTENCİ", sinif: "11-A" },
    { no: "2362", ad: "BURCU", soyad: "DEMİREL", sinif: "11-A" },
    { no: "2366", ad: "ŞEHRİ", soyad: "DEĞİRMENCİ", sinif: "11-A" },

    // 11. Sınıf / B Şubesi
    { no: "2274", ad: "ABDULLAH TALHA", soyad: "AKDENİZ", sinif: "11-B" },
    { no: "2304", ad: "İSMAİL BEDİRHAN", soyad: "AKDAŞ", sinif: "11-B" },
    { no: "2311", ad: "MERVE", soyad: "DALMAZ", sinif: "11-B" },
    { no: "2313", ad: "BETÜL", soyad: "GÜLER", sinif: "11-B" },
    { no: "2320", ad: "TARIK", soyad: "ŞİMŞEK", sinif: "11-B" },
    { no: "2323", ad: "ALPEREN", soyad: "KOCA", sinif: "11-B" },
    { no: "2324", ad: "YİĞİT CAN", soyad: "TOY", sinif: "11-B" },
    { no: "2333", ad: "ESRA", soyad: "İNCE", sinif: "11-B" },
    { no: "2335", ad: "ELİF", soyad: "İNCE", sinif: "11-B" },
    { no: "2336", ad: "ZEYNEP", soyad: "UMAY", sinif: "11-B" },
    { no: "2339", ad: "ERTUĞRUL SAMET", soyad: "DURAK", sinif: "11-B" },
    { no: "2343", ad: "ALİ", soyad: "KURTOĞLU", sinif: "11-B" },
    { no: "2354", ad: "ZEYNEP DİYAR", soyad: "DEMİRCİ", sinif: "11-B" },
    { no: "2363", ad: "CANSU", soyad: "DEVREZ", sinif: "11-B" },
    { no: "2364", ad: "AHMET", soyad: "KILIÇ", sinif: "11-B" },

    // 11. Sınıf / C Şubesi
    { no: "2371", ad: "NAZLI", soyad: "ÇETİNTAŞ", sinif: "11-C" },
    { no: "2378", ad: "ZEYNEP", soyad: "AKSOY", sinif: "11-C" },
    { no: "2379", ad: "SAMET", soyad: "KARAKOÇ", sinif: "11-C" },
    { no: "2381", ad: "MELEK EBRU", soyad: "ÇAPAR", sinif: "11-C" },
    { no: "2386", ad: "FATMANUR", soyad: "ÖZKORUKCU", sinif: "11-C" },
    { no: "2387", ad: "AYŞE NAZ", soyad: "BÜYÜKKÖLEŞ", sinif: "11-C" },
    { no: "2389", ad: "GAMZEGÜL", soyad: "AYAZ", sinif: "11-C" },

    // 12. Sınıf / A Şubesi
    { no: "2201", ad: "İKRA", soyad: "DİŞÇEKEN", sinif: "12-A" },
    { no: "2202", ad: "SAMET", soyad: "KONUK", sinif: "12-A" },
    { no: "2203", ad: "ELİF NİSA", soyad: "OKUDUCU", sinif: "12-A" },
    { no: "2204", ad: "ELANUR", soyad: "SÜREK", sinif: "12-A" },
    { no: "2205", ad: "YASİN EMİRCAN", soyad: "SİVRİ", sinif: "12-A" },
    { no: "2208", ad: "ESRA", soyad: "KUMSAR", sinif: "12-A" },
    { no: "2209", ad: "YAŞAR", soyad: "YAZAN", sinif: "12-A" },
    { no: "2210", ad: "OKTAY", soyad: "ŞARE", sinif: "12-A" },
    { no: "2211", ad: "TAHA CAN", soyad: "ÖZBİLEN", sinif: "12-A" },
    { no: "2213", ad: "SEFA", soyad: "AÇIKBAŞ", sinif: "12-A" },
    { no: "2214", ad: "HALİL", soyad: "AÇIKBAŞ", sinif: "12-A" },
    { no: "2215", ad: "AYŞENUR", soyad: "TOPRAK", sinif: "12-A" },
    { no: "2216", ad: "HAZAL", soyad: "DALMAZ", sinif: "12-A" },
    { no: "2217", ad: "FURKAN", soyad: "TEKİN", sinif: "12-A" },

    // 12. Sınıf / AV Şubesi
    { no: "209", ad: "MELEK", soyad: "BOSTANOĞLU", sinif: "12-AV" },
    { no: "229", ad: "ELİF", soyad: "KILIÇ", sinif: "12-AV" },
    { no: "243", ad: "ÖZGÜR", soyad: "HATIRLI", sinif: "12-AV" },
    { no: "246", ad: "MERVE", soyad: "KÖLE", sinif: "12-AV" },
    { no: "259", ad: "BEYZANUR", soyad: "KESKİN", sinif: "12-AV" },
    { no: "275", ad: "ALEYNA", soyad: "ÖZDEMİR", sinif: "12-AV" },

    // 12. Sınıf / B Şubesi
    { no: "2250", ad: "BURAK", soyad: "TORUN", sinif: "12-B" },
    { no: "2251", ad: "EFE", soyad: "ZORLU", sinif: "12-B" },
    { no: "2254", ad: "EMİR", soyad: "ERDOĞANOĞLU", sinif: "12-B" },
    { no: "2255", ad: "MELİSA", soyad: "YUMUŞAK", sinif: "12-B" },
    { no: "2259", ad: "İLAYDA", soyad: "YASİN", sinif: "12-B" },
    { no: "2260", ad: "AZİM", soyad: "KAYMAKCI", sinif: "12-B" },
    { no: "2261", ad: "ELİF", soyad: "KARABIYIKOĞLU", sinif: "12-B" },
    { no: "2262", ad: "RAVZANUR", soyad: "ELMACIOĞLU", sinif: "12-B" },
    { no: "2263", ad: "MEHDİ TAHA", soyad: "ÇALIŞAN", sinif: "12-B" },
    { no: "2264", ad: "ZEYNEP", soyad: "KIZILKAYA", sinif: "12-B" },
    { no: "2265", ad: "İLYAS YİĞİT", soyad: "ASLAN", sinif: "12-B" },
    { no: "2266", ad: "VEYİS", soyad: "ÖZÇUBUKCU", sinif: "12-B" },
    { no: "2267", ad: "BARİŞ", soyad: "TÜNEDEN", sinif: "12-B" },
    { no: "2268", ad: "HÜSEYİN", soyad: "ELTUĞRAL", sinif: "12-B" },
    { no: "2269", ad: "YAREN ECRİN", soyad: "KARADAŞ", sinif: "12-B" },
    { no: "2271", ad: "MEHMET BERAT", soyad: "EMEKLİ", sinif: "12-B" },
    { no: "2272", ad: "YAĞMUR", soyad: "KARAHAYDAR", sinif: "12-B" },
    { no: "2273", ad: "SİNEM", soyad: "VARLI", sinif: "12-B" },
    { no: "2276", ad: "HASAN", soyad: "ILGAZ", sinif: "12-B" },
    { no: "2277", ad: "EYLÜL", soyad: "KASTAMONULUGIL", sinif: "12-B" }
];